INSERT INTO VOTE (UID_VOTE, VALUE_ENUM, FK_SCHEDULE_UID, FK_ASSOCIATED_UID)
VALUES (1, 'YES', 1, 1);

INSERT INTO VOTE (UID_VOTE, VALUE_ENUM, FK_SCHEDULE_UID, FK_ASSOCIATED_UID)
VALUES (2, 'NOT', 2, 2);

INSERT INTO VOTE (UID_VOTE, VALUE_ENUM, FK_SCHEDULE_UID, FK_ASSOCIATED_UID)
VALUES (3, 'YES', 3, 3);