CREATE TABLE PUBLIC.ASSOCIATED (
PK_ASSOCIATED BIGINT NOT NULL, CONSTRAINT PK_ASSOCIATED PRIMARY KEY (PK_ASSOCIATED),
NAME VARCHAR (255) NOT NULL
);

COMMENT ON TABLE PUBLIC.ASSOCIATED IS 'Tabela com as informações dos meta itens.';
COMMENT ON COLUMN PUBLIC.ASSOCIATED.PK_ASSOCIATED IS 'Identificador único da tabela META.';
COMMENT ON COLUMN PUBLIC.ASSOCIATED.NAME IS 'Nome do meta.';