CREATE TABLE ASSOCIATED (
UID_ASSOCIATED BIGINT NOT NULL,
NAME VARCHAR(200) NOT NULL,
CPF VARCHAR(11) UNIQUE NOT NULL,
CREATED_AT TIMESTAMP NOT NULL
);

COMMENT ON TABLE ASSOCIATED IS 'Tabela com as informações dos associados.';
COMMENT ON COLUMN ASSOCIATED.UID_ASSOCIATED IS 'Identificador único da tabela ASSOCIATED.';
COMMENT ON COLUMN ASSOCIATED.NAME IS 'Nome do associado.';
COMMENT ON COLUMN ASSOCIATED.CPF IS 'CPF do associado.';
COMMENT ON COLUMN ASSOCIATED.CREATED_AT IS 'Data de criação do associado.';