CREATE TABLE SCHEDULE (
UID_SCHEDULE BIGINT NOT NULL,
TITLE VARCHAR(100) NOT NULL,
STATUS VARCHAR(50) NOT NULL,
DESCRIPTION VARCHAR(255),
DURATION_ESTIMATE BIGINT,
END_TIME TIMESTAMP,
START_TIME TIMESTAMP,
RESULT VARCHAR(50) NOT NULL
);

COMMENT ON TABLE SCHEDULE IS 'Tabela com as informações das pautas.';
COMMENT ON COLUMN SCHEDULE.UID_SCHEDULE IS 'Identificador único da tabela SCHEDULE.';
COMMENT ON COLUMN SCHEDULE.TITLE IS 'Titúlo da pauta.';
COMMENT ON COLUMN SCHEDULE.DESCRIPTION IS 'Descrição da pauta.';
COMMENT ON COLUMN SCHEDULE.DURATION_ESTIMATE IS 'Duração total estimada da pauta em minutos.';
COMMENT ON COLUMN SCHEDULE.STATUS IS 'Status da sessão da pauta.';
COMMENT ON COLUMN SCHEDULE.START_TIME IS 'Momento do início da sessão da pauta.';
COMMENT ON COLUMN SCHEDULE.END_TIME IS 'Momento do final da sessão da pauta.';
COMMENT ON COLUMN SCHEDULE.RESULT IS 'Enum que contém o resultado da pauta.';